server:
  port: 30000
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: gulimall-third-party


#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

    #关闭thymeleaf缓存
  thymeleaf:
    cache: false

  session:
    store-type: redis

logging:
  level:
    com.feng.gulimall: debug


#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'